spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: http://keycloak.192.168.11.240.nip.io/auth/realms/demo/protocol/openid-connect/auth
            token-uri: http://keycloak.192.168.11.240.nip.io/auth/realms/demo/protocol/openid-connect/token
            user-info-uri: http://keycloak.192.168.11.240.nip.io/auth/realms/demo/protocol/openid-connect/userinfo
            jwk-set-uri: http://keycloak.192.168.11.240.nip.io/auth/realms/demo/protocol/openid-connect/certs
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: login-app
            client-secret: e712ef31-29c6-48f4-bc47-d98da0248b5e
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: api,profile
server:
  port: 8001

logging:
  level:
    ROOT: warn
    org.springframework.security: trace
    com.pksheldon4: debug