authserverUri: ${AUTHSERVER_URI:http://keycloak.192.168.11.240.nip.io}

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: ${authserverUri}/auth/realms/demo/protocol/openid-connect/auth
            token-uri: ${authserverUri}/auth/realms/demo/protocol/openid-connect/token
            user-info-uri: ${authserverUri}/auth/realms/demo/protocol/openid-connect/userinfo
            jwk-set-uri: ${authserverUri}/auth/realms/demo/protocol/openid-connect/certs
            user-name-attribute: preferred_username
        registration:
          keycloak:
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: api,openid,profile
server:
  port: ${SERVER_PORT:8001}

logging:
  level:
    ROOT: info
    org.springframework.security: trace
    com.pksheldon4: debug